import Head from 'next/head'

export default function Home() {
  return (
    <div className='bg-white'>
      <Head>
        <title>James Sullivan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
