import Head from 'next/head'

export default function Home() {
  return (
    <div className='bg-white overflow-scroll'>
      <Head>
        <title>James Sullivan</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;500&display=swap" rel="stylesheet"></link>
      </Head>
    </div>
  )
}
