import React from 'react'

export default function Window() {
  return (
    <div className=' min-h 3/4ml-5 border-2 w-3/5 bg-special-grey my-20'>
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
        window
    </div>
  )
}
